/**
 * Static web assets served by the plugin over webServer routes:
 *
 *   /dsh-web-push/sw.js                  — the service worker (push + click)
 *   /dsh-web-push/manifest.webmanifest   — minimal PWA manifest (A2HS / icons)
 *   /dsh-web-push/icon.svg               — notification + home-screen icon
 *
 * The service worker scope is /dsh-web-push/ (its own directory), which is all
 * the Push API needs: the subscription is bound to the registration, and the
 * `notificationclick` handler may open any same-origin URL (the DSH root '/').
 */
/** Build the service worker JavaScript served at /dsh-web-push/sw.js. */
export function serviceWorkerSource() {
    return `/* dsh-web-push service worker — generated by the dsh-web-push plugin */
self.addEventListener('install', () => {
  self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// Origin liveness, probed once per worker lifetime: quick-tunnel restarts
// orphan this worker's domain, and opening ANY url on a dead origin lands on
// a Cloudflare error page (1016/1033). A dead-origin click is a silent no-op;
// opening DSH on the live URL re-subscribes and heals everything.
let originAlive = undefined // undefined = unknown, true/false = cached verdict
const probeOrigin = async () => {
  try {
    const res = await fetch('/dsh-web-push/sw.js', { cache: 'no-store' })
    originAlive = res.status === 200 // 404/5xx from the edge = dead tunnel
  } catch { originAlive = false } // network failure = dead domain
  return originAlive
}

self.addEventListener('push', (event) => {
  if (originAlive === undefined) void probeOrigin() // pre-warm; don't block display
  let data = {}
  try {
    data = event.data ? event.data.json() : {}
  } catch (error) {
    data = { title: 'DSH', body: event.data ? event.data.text() : '' }
  }
  const title = data.title || 'DSH'
  event.waitUntil(self.registration.showNotification(title, {
    body: data.body || '',
    tag: data.tag || 'dsh-web-push',
    renotify: true,
    icon: data.icon || '/dsh-web-push/icon.svg',
    badge: '/dsh-web-push/icon.svg',
    data: { url: data.url || '/', session: data.session },
  }))
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const data = event.notification.data || {}
  const url = data.url || '/'
  const sessionId = data.session
  event.waitUntil((async () => {
    if (originAlive === undefined) await probeOrigin()
    if (!originAlive) return // dead origin: no action beats an error page
    const clientList = await self.clients.matchAll({ type: 'window', includeUncontrolled: true })
    for (const client of clientList) {
      if ('focus' in client) {
        // Live tab: steer it in place — no reload, no lost drafts. The page
        // listens for 'dsh-web-push:open' and calls uiWorkspace.openSession.
        if (sessionId) {
          client.postMessage({ type: 'dsh-web-push:open', session: sessionId })
          return client.focus()
        }
        try { if (client.navigate && client.url !== new URL(url, self.location.origin).href) await client.navigate(url) } catch (error) {}
        return client.focus()
      }
    }
    // Cold open carries the session in the URL; the page's deep-link shim
    // reads it once on boot and switches to that session.
    return self.clients.openWindow(url)
  })())
})
`;
}
const ICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
<rect width="512" height="512" rx="96" fill="#4D6BFE"/>
<path d="M256 96c-70 0-128 52-128 118v74l-30 62c-4 9 2 18 12 18h66c14 30 44 48 80 48s66-18 80-48h66c10 0 16-9 12-18l-30-62v-74C384 148 326 96 256 96z" fill="#fff"/>
<circle cx="256" cy="232" r="44" fill="#4D6BFE"/>
</svg>
`;
/** Build the web manifest served at /dsh-web-push/manifest.webmanifest. */
export function manifestSource() {
    return JSON.stringify({
        name: 'DeepSeek Harness',
        short_name: 'DSH',
        description: 'DeepSeek Harness web push notifications',
        start_url: '/',
        display: 'standalone',
        background_color: '#111318',
        theme_color: '#4D6BFE',
        icons: [
            { src: '/dsh-web-push/icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
        ],
    }, null, 2);
}
export { ICON_SVG };
